name: docker

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-20.04

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event.pull_request.merged == true }}
          tags: salesloft/ruby-jemalloc:2.6.10-buster-slim
          build-args: RUBY_MAJOR=2.6,RUBY_VERSION=2.6.10,RUBY_GEMS_VERSION=3.0.3.1,RUBY_DOWNLOAD_SHA256=5fd8ded51321b88fdc9c1b4b0eb1b951d2eddbc293865da0151612c2e814c1f2
